services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - 80:80
    environment:
      VITE_PUBLIC_KEY: Jl7Fl8Ee64w=
      VITE_IDLE_TIMEOUT: 30
      VITE_API_URL: /carepro-api
      VITE_REPORTING_URL: "#"

  dotnet-api:
    image: excelazmin/carepro-api:latest
    expose:
      - "80"

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - vite-react-app
  #     - dotnet-api
